version: "3.9"
services:
  amq1:
    image: "amq-base-image"
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - /Users/robertfloor/tutorials/packer/packer-docker-ansible/data:/data

  amq2:
    image: "amq-base-image"
    ports:
      - "8162:8161"
      - "61617:61616"
    volumes:
      - /Users/robertfloor/tutorials/packer/packer-docker-ansible/data:/data
