apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: amq
    image: rflfrubix/amq-base0image
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
