---
- hosts: all
  vars:
    - activemq:
        home: /opt/amq/amq-broker-7.10.0
        instance_home: /opt/amq/amq-broker
    - activemq_service_user: amq
    - activemq_service_group: amq
    - activemq_prometheus_enabled: true


  tasks:
    - name: message
      debug: msg="Container {{ inventory_hostname }}"
      become: yes
    - name: install
      package: name=git state=latest
      become: yes
      become_user: amq
    - name: "Configure prometheus metrics"
      when: activemq_prometheus_enabled
      block:
        - name: Ensure lib is available to instance
          ansible.builtin.copy:
            src: "{{ activemq.home }}/lib/artemis-prometheus-metrics-plugin-1.1.0.redhat-00002.jar"
            dest: "{{ activemq.instance_home }}/lib/"
            remote_src: yes
            owner: "{{ activemq_service_user }}"
            group: "{{ activemq_service_group }}"
            mode: 0644

        - name: Configure metrics plugin
          xml:
            path: "/opt/amq/amq-broker/etc/broker.xml"
            xpath: /conf:configuration/core:core/core:metrics/core:plugin
            attribute: class-name
            value: org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core