---
kind: Pod
apiVersion: v1
metadata:
  name: amq-pv-pod-2
spec:
  volumes:
    - name: my-pv-storage
      persistentVolumeClaim:
       claimName: my-pv-claim
  containers:
    - name: amq2
      image: rflfrubix/amq:latest
      volumeMounts:
        - mountPath: "/data"
          name: my-pv-storage
