apiVersion: v1
kind: Service
metadata:
  name: ha-amq-service
  labels:
    deploy: example
spec:
  type: NodePort
  ports:
  - port: 8161
    targetPort: 8161
    name: web
    nodePort: 30007
  selector:
    deploy: example
