kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: amq-ha-deployment
  labels:
    deploy: example
spec:
  # A deployment's specification really only
  # has a few useful options
  serviceName: "amq-broker"


  # 1. How many copies of each pod do we want?
  replicas: 2

  # 2. How do want to update the pods?

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: example

  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: example
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: amq
          image: rflfrubix/amq:latest
          volumeMounts:
            - mountPath: "/data"
              name: my-pv-storage
          readinessProbe:
            httpGet:
              path: /console
              port: 8161
            initialDelaySeconds: 10
            periodSeconds: 3
